### ISSUE TITLE
Does not play well with bootstrap-validator

### ISSUE THREAD

**Issue by jsumners** [wenzhixin/bootstrap-show-password#12]
Given a simple authentication form, with bootstrap-show-password attached to the password field, validation of the form via bootstrap-validator[1] fails.

[1] -- https://github.com/1000hz/bootstrap-validator

**Comment by jpalmieri** [comment]
This may be resolved with my PR: https://github.com/wenzhixin/bootstrap-show-password/pull/46

I'm not sure what your issue was (and yeah, I know this was hella long ago), but mine was a rendering issue because of a nested input group. My PR adds an option to *not* wrap the elements in an input group.

Also, a note for posterity: no one should be using bootstrap-validator if they have the option. The maintainer has abandoned it. See https://github.com/1000hz/bootstrap-validator/issues/656

**Comment by jsumners** [comment]
I have absolutely no idea. I forgot this was even a thing.

**Comment by jpalmieri** [comment]
Welcome to the past! 🚀
